// <auto-generated />
using Barlang.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Barlang.Migrations
{
    [DbContext(typeof(BarlangDbContext))]
    [Migration("20250930064333_sqlite.local_migration_519")]
    partial class sqlitelocal_migration_519
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("Barlang.Models.BarlangModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Hossz")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kiterjedes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Magassag")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Melyseg")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telepules")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Barlangok");
                });
#pragma warning restore 612, 618
        }
    }
}
